server:
  port: 8080

spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view: false

# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml